[package]
name = "wheresmyinternet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "3.2"
seq-macro = "0.3.5"